removed USING_CMAKE macro
It's used from here on, anymore and it doesn't work correctly with
configure/autogen.sh anyway: While CMake's configure_file() replaces
unknown @...@ parts with an empty string, configure apparently leaves
them untouched, so that one might get error messages like
	error: token "@" is not valid in preprocessor expressions
when using the macro.